apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application-dev.yml: |
    server:
      port: 8080
    eureka:
      client:
        enabled: false
    spring:
      cloud:
        discovery:
          enabled: false
        gateway:
          mvc:
            routes:
              - id: backend-user
                uri: http://backend-user-service:8080
                predicates:
                  - Path=/api/user/**
                filters:
                  - AddAuthenticationHeader
              - id: backend-alim
                uri: http://backend-alim-service:8080
                predicates:
                  - Path=/api/alim/**
                filters:
                  - AddAuthenticationHeader
              - id: backend-news
                uri: http://backend-news-service:8080
                predicates:
                  - Path=/api/news/**
                filters:
                  - AddAuthenticationHeader