apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  annotations:
    reloader.skakater.com/auto: "true"
spec:
  replicas: 3  # 원하는 파드 복제본 수 (기본값: 1)
  selector:
    matchLabels:
      app: api-gateway  # 템플릿의 labels와 일치해야 함
  template:
    metadata:
      labels:
        app: api-gateway  # selector와 일치해야 함
    spec:
      containers:
      - name: api-gateway
        image: rnals12/api-gateway:0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
#        livenessProbe:
#          httpGet:
#            path: /api-gateway/v1/k8s/liveness  # 스프링 부트 생존 상태 엔드포인트
#            port: 8080
#          initialDelaySeconds: 30   # 컨테이너 시작 후 첫 검사까지 대기
#          periodSeconds: 5          # 5초마다 체크
#          failureThreshold: 3       # 3회 연속 실패 시 컨테이너 재시작
#          timeoutSeconds: 3         # 3초 내 응답 필요
#
#        # Readiness Probe 추가 (트래픽 유입 제어용)
#        readinessProbe:
#          httpGet:
#            path: /backend/user/v1/k8s/readiness  # 스프링 부트 준비 상태 엔드포인트
#            port: 8080
#          initialDelaySeconds: 30   # 컨테이너 시작 후 첫 검사까지 대기
#          periodSeconds: 5          # 5초마다 체크
#          failureThreshold: 3       # 3회 연속 실패 시 서비스 트래픽 중지
#          timeoutSeconds: 3         # 3초 내 응답 필요
        volumeMounts:
          - mountPath: /etc/config
            name: api-gateway-config-volume
      volumes:
        - name: api-gateway-config-volume
          configMap:
            name: api-gateway-config
            items:
              - key: application-dev.yml
                path: application-dev.yml
        - name: api-gateway-secret-volume
          Secret:
            secretName: api-gateway-secret
            items:
              - key: application-secret.yml
                path: application-secret.yml
