apiVersion: v1
kind: Secret
metadata:
  name: backend-user-secret
  namespace: default
type: Opaque
stringData:
  application-secret.yml: |
    spring:
      datasource:
        username: user
        password: 1234
    jwt:
      expires-in: 86400 # 1day
      mobile-expires-in: 31536000
      table-expires-in: 31536000
      secret: AADfaskllew32dsfasdTG764Gdslkj298GsWg86GAADfaskllew32dsfasdTG764Gdslkj298GsWg86G