apiVersion: v1
kind: Service
metadata:
  name: backend-user-service
  labels:
    app: backend-user-service
spec:
  type: ClusterIP
  selector:
    app: backend-user-service
  ports:
    - port: 8080
      targetPort: 8080