apiVersion: v1
kind: Service
metadata:
  name: alim-service
  labels:
    app: alim-service
spec:
  type: NodePort
  selector:
    app: alim-service
  ports:
    - port: 8080
      targetPort: 8080
      #nodePort: 31003