apiVersion: apps/v1
kind: Deployment
metadata:
  name: alim-service
  labels:
    app: alim-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alim-service
  template:
    metadata:
      labels:
        app: alim-service
    spec:
      containers:
        - name: alim-service
          image: leenagyoung/alim-service:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: alim-config
                  key: SPRING_PROFILES_ACTIVE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: alim-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alim-secret
                  key: DB_PASSWORD